name: pre-commit

on:
  pull_request:
  push:

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v3
    - name: Install shellcheck
      # used by actionlint
      run: |
        sudo apt-get update
        sudo apt-get install shellcheck -y
    - name: Install actionlint
      # https://github.com/rhysd/actionlint/blob/main/docs/install.md
      run: |
        bash <(curl https://raw.githubusercontent.com/rhysd/actionlint/main/scripts/download-actionlint.bash)
        echo "$PWD" >> "$GITHUB_PATH"

    - uses: pre-commit/action@v3.0.0
      with:
        extra_args: "--all-files"