name: Test the package with pytest

on: [push, pull_request, workflow_dispatch]

jobs:
  pytest:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.6", "3.7", "3.8", "3.9", "3.10"]
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install Boost Python
        env:
          python_version: ${{ matrix.python-version }}
          boost_version: "1.79.0"
        run: |
          python_version_abbr="${python_version//./}"
          boost_version_alias="boost_${boost_version//./_}"

          sudo apt-get update
          sudo apt-get install gcc -y
          sudo apt-get install g++ -y

          wget "https://boostorg.jfrog.io/artifactory/main/release/${boost_version}/source/${boost_version_alias}.tar.gz"
          tar -xf "${boost_version_alias}.tar.gz"

          cd "${boost_version_alias}"
          ./bootstrap.sh --with-python=python
          sudo ./b2 cxxflags="-fPIC" install --with-python

          cd ${{ github.workspace }}
          sudo ln -s "/usr/local/lib/libboost_python${python_version_abbr}.a" "/usr/local/lib/libboost_python.a"
      - name: Install dependencies
        run: |
          pip install pytest
          pip install Pillow
          pip install kiwisolver
          pip install gensim
          pip install lxml
      - name: Build easygraph
        run: |
          python setup.py build_ext -l boost_python -L "/usr/local/lib" -I "/usr/local/include"
      - name: Install easygraph
        run: |
          python setup.py install
      - name: Test with pytest
        run: |
          cd ${{ github.workspace }}
          pytest --disable-warnings
